name          'timeincoss-sysdig'
version       '0.2.0'
source        'git://github.com/timeincoss/puppet-sysdig.git'
author        'Gareth Rushgrove'
license       'Apache 2.0'
summary       'Install sysdig from the official repositories'
description   'Install sysdig from the official repositories'
project_page  'https://github.com/timeincoss/puppet-sysdig'

dependency 'puppetlabs/stdlib'
dependency 'puppetlabs/apt'
